### ISSUE TITLE
Can not import Record from cyber_record.record

### ISSUE THREAD

**Issue by Gaoming1985** [daohu527/cyber_record#25]
Hi, when try to import Record from cyber_record.record, the record_pb2.py throw an error: 

module "google.protobuf.descriptor" has no attribute '_internal_create_key'

would you give some advice?

Thanks,

**Comment by daohu527** [comment]
what's your version of `protobuf`? You can try
```
pip3 install --upgrade protobuf
```

**Comment by Gaoming1985** [comment]
Hi, the probelm is gone after I update my protobuf to the latest version(3.20.1) on Ubuntu 20.04. Thanks very much for such wonderful tools. 👍
