### ISSUE TITLE
AttributeError: 'Record' object has no attribute '_write_file_header_record'

### ISSUE THREAD

**Issue by yy7410** [daohu527/cyber_record#28]
运行test_write_record.py报错
AttributeError: 'Record' object has no attribute '_write_file_header_record'

**Comment by daohu527** [comment]
## version
what's your version of `cyber_record`, you can use below cmd to find the version of it.
```
pip3 list | grep cyber_record
```

## update
the latest version is `0.1.1` which will support `_write_file_header_record`, other versions may only support read. You can update the version by. 
```
pip3 install cyber_record  --no-deps
```

by the way, there is a protobuf error with setup.py, you should force install by above cmd, I will fix it asap!

**Comment by yy7410** [comment]
谢谢，升级0.1.1版本解决了错误

**Comment by daohu527** [comment]
#30 fix install protobuf dependency version error. 

Close this ticket based on the comments above. If the problem persists, feel free to reopen it. Thank you.
