### ISSUE TITLE
Remove print(header) from reader or use a flag to control

### ISSUE THREAD

**Issue by YuqiHuai** [daohu527/cyber_record#38]
Hi!

Thank you for the great tool!

I am wondering if the following line
https://github.com/daohu527/cyber_record/blob/b00546d041f382793a9f2454f1a8bf7c3722ce79/cyber_record/reader.py#L56

should be removed or controllable through a boolean flag, so it does not print information to the console if I do not need it.

**Comment by daohu527** [comment]
Thanks for your advice! 
Next step, I will repalce print to log. Maybe this weekend.

**Comment by YuqiHuai** [comment]
Great! Thanks! I have been using your tools and they work well so far. I temporarily commented out the line myself.

**Comment by daohu527** [comment]
fix the log, and you can update the new version `pip3 install cyber_record -U`
