### ISSUE TITLE
cyber_record：未找到命令(command not found)

### ISSUE THREAD

**Issue by yangls06** [daohu527/cyber_record#47]
After `pip3 install cyber_record`, I run the following command in my terminal:
`cyber_record info -f 0818_test_data/20220818160638.record.00000`

And get the "cyber_record：未找到命令(command not found)" error.

What happened?

**Comment by daohu527** [comment]
what operating system are you using?  I already tested in ubuntu 18.04

Here are some similar problem you can refer to

https://stackoverflow.com/questions/34946777/python-entry-point-commandline-script-not-found-when-installing-with-user-flag

**Comment by yangls06** [comment]
I am using Ubuntu20.04.

**Comment by yangls06** [comment]
Can you support protobuf version <=3.17.0? Our car use protobuf=3.14.0 to produce cyber record.

![image](https://user-images.githubusercontent.com/1796246/188355404-76a56533-5c4e-45b3-a860-746402b937e9.png)

**Comment by daohu527** [comment]
I haven't tested 3.14 so I can't guarantee this will work, you can try force install cyber_record and have a try.
```
pip3 install cyber_record --no-deps
```

**Comment by yangls06** [comment]
Hi daohu527, I want to fork your project to modify code to adapt the 3.14 proto, can you tell me where I should modify?

Another question is: how to generate the cyber/proto/record_pb2.py file?  It said that "# Generated by the protocol buffer compiler.  DO NOT EDIT!"

Looking forward to your instructions. Thank you very much.

**Comment by daohu527** [comment]
In fact, I don't know what will go wrong, you can try it first and then give feedback.

this file is generate by `cyber/proto/record.proto`. You don't need to modify it unless necessary, for example, you have modified this proto file

**Comment by yangls06** [comment]
OK. I will give it a try. Thanks.

**Comment by yangls06** [comment]
I can't find the file `cyber/proto/record.proto`. Can you share it?  Will the result file `cyber/proto/record_pb2.py` change with different protobuf version (from 3.20 to 3.14 )?

**Comment by daohu527** [comment]
The file is here https://github.com/ApolloAuto/apollo/blob/master/cyber/proto/record.proto

This has nothing to do with the protobuf version, in fact, it only has to do with the format of the record.

**Comment by yangls06** [comment]
Got it. Thank.
