### ISSUE TITLE
Invalid proto descriptor for file "":   : Missing field: FileDescriptorProto.name.

### ISSUE THREAD

**Issue by GabrielZZZ** [daohu527/cyber_record#48]
Hello, I am using this tool to try to parse the demo record file (demo_sensor_data_for_vision.record), and I only modified the related file name in the test_parser_message.py. Now I encountered this issue (I am calling the python code inside the apollo container):
![image](https://user-images.githubusercontent.com/42797233/191971027-b0ae23d5-9d18-41ff-825c-cef30ce96907.png)

By the way, I also encountered the command not found issue by directly calling cyber_record from the command line in container, and I am using Ubuntu 20.04.

This is a great tool. Anyway how to solve these issues?

**Comment by GabrielZZZ** [comment]
The record file to parse, information:
![image](https://user-images.githubusercontent.com/42797233/191975429-58811fd1-6fee-4822-b810-a1b0959cb434.png)

**Comment by daohu527** [comment]
The problem may be with the record file. You know this tool is not need any message proto file and just read from record file itself

**Comment by GabrielZZZ** [comment]
I agree. But I downloaded these records from the Apollo demo, and they can be played by the cyber_recorder. I can not see the problem inside them. I also tested another file from the tutorial. Same issue.
![image](https://user-images.githubusercontent.com/42797233/191986269-a37c942b-12e7-4bd0-9b16-8bdbd8d6f518.png)
record file: [demo_sensor_data_for_vision.tar.xz](https://apollo-system.cdn.bcebos.com/dataset/6.0_edu/demo_sensor_data_for_vision.tar.xz)

**Comment by daohu527** [comment]
The `/apollo/sensor/camera/front_6mm/image` channel have no desc,I fixed the error and it would skip parsing the channel.

**Comment by GabrielZZZ** [comment]
@daohu527 Hi, thanks for the reply. Actually, the goal for me to use this tool is to parse the image from the exsiting recordings. Does the fix mean this tool no longer supports this function?

**Comment by GabrielZZZ** [comment]
Thank you! I have updated the tool, now it can read the image information from the databag now. However, when coming to the parsing part, it now outputs the error:
![image](https://user-images.githubusercontent.com/42797233/192230133-096adef6-4f6d-486a-a0a9-c8f7e3c8dfe5.png)
Is there any solution to successfully extract the image from this bag? I really want to use it.

**Comment by daohu527** [comment]
No, this tool has no proto dependencies, so you can use apollo cyber_recorder to decompress

**Comment by daohu527** [comment]
Maybe I'll provide a cmd to recover the record.

**Comment by GabrielZZZ** [comment]
That would be very kind. Thanks a lot

**Comment by daohu527** [comment]
@GabrielZZZ I add the recover cmd and it works, I have unzipped the image from the record file.

You can follow the [readme](https://github.com/daohu527/cyber_record#recover) to recover the file.
