### ISSUE TITLE
Error about cyber_record.record

### ISSUE THREAD

**Issue by MLunar** [daohu527/cyber_record#60]
Hello!
Record from cyber_record.record can't work when the 'xxx.record' was obtained by the Apollo-edu version. The error is: _Conflict register for file "modules/common/proto/error_code.proto": apollo.common.StatusPb is already defined in file "modules/common_msgs/basic_msgs/error_code.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication._

But it can work perfectly when the 'xxx.record' was obtained by the Apollo 7.0 version.

How can I solve this problem? Think you very much!

**Comment by daohu527** [comment]
edu moved messages to the common_msg, thus causing the problem. But I don't depend on this, so are you having problems parsing packages or something else?

**Comment by MLunar** [comment]
The error occurred in `Record`, the details: 

> Traceback (most recent call last):
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 235, in _add_dependency
>     self.desc_pool.FindFileByName(file_desc_proto.name)
> KeyError: "Couldn't find file modules/common/proto/error_code.proto"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "d:\Documents\codes\apollo\data_record.py", line 10, in <module>
>     record = Record(file_name)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\record.py", line 104, in __init__
>     self._open(f, mode, allow_unindexed)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\record.py", line 298, in _open
>     if mode == 'r': self._open_read(f)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\record.py", line 320, in _open_read
>     self._reader.start_reading()
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 74, in start_reading
>     self._create_message_type_pool()
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 246, in _create_message_type_pool
>     self._add_dependency(proto_desc)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 232, in _add_dependency
>     self._add_dependency(dependency)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 232, in _add_dependency
>     self._add_dependency(dependency)
>   File "C:\Users\Administrator\anaconda3\lib\site-packages\cyber_record\reader.py", line 237, in _add_dependency
>     self.desc_pool.Add(file_desc_proto)
> TypeError: Couldn't build proto file into descriptor pool!
> Invalid proto descriptor for file "modules/common/proto/error_code.proto":

**Comment by daohu527** [comment]
There may be a problem with the record, you may need to update the code and try. 

Maybe `modules/common/proto/error_code.proto` is an old message in edu version
