### ISSUE TITLE
How to write a muiltiple channels recoder?

### ISSUE THREAD

**Issue by Weilesscodeless** [daohu527/cyber_record#62]
My codes like this:
with Record("xxx/output.record", mode='a') as w_record:
              w_record.write('/ins/gps', GPS_, int(stamp))
              w_record.write('/ins/imu', IMU_, int(stamp))
and I can this see these messsges in recoder info. But It wont work ,when I play this bag in Apollo.
Only first item showed in monitor .

**Comment by daohu527** [comment]
If `cyber_record info` can normally display the number of `/ins/imu'`, it may be a parsing problem of playing messages?
