### ISSUE TITLE
TypeError: PointCloudBuilder.build() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by Srikar-Chaganti** [daohu527/cyber_record#63]
Hi,

I'm using radiate dataset, which has csv file for lidar point cloud. The csv file has (x, y, z, intensity, ring) data. Here I'm trying to create a record file for Apollo env. When I feed this csv file, I'm getting an error as TypeError: PointCloudBuilder.build() takes from 3 to 4 positional arguments but 5 were given.

I have also written a function for building from csv in the PointCloudBuilder() but still getting this error

##### Building from CSV ######
 def build_from_csv(self, csv_file_name, frame_id, t=None):
        pb_point_cloud = pointcloud_pb2.PointCloud()

        if t is None:
            t = time.time()

        self._build_header(pb_point_cloud.header, t=t, frame_id=frame_id)
        pb_point_cloud.frame_id = frame_id
        pb_point_cloud.measurement_time = t

        # Open and read the CSV file
        with open(csv_file_name, 'r') as csv_file:
            csv_reader = csv.reader(csv_file)
            next(csv_reader)  # Skip header row if present

            for row in csv_reader:
                x, y, z, intensity = map(float, row)  # Assuming CSV columns are in this order
                point = pb_point_cloud.point.add()
                point.x = x
                point.y = y
                point.z = z
                point.intensity = intensity

        self._sequence_num += 1
        return pb_point_cloud

This function is implemented in the dataset converter for radiate dataset for record to run on Apollo
## Implemented in dataset converter #######
      elif 'lidar_bev_image' in c:
        pb_msg = pc_builder.build_from_csv(f2, id, t/1e9, LIDAR_TRANSFORM) ##This is where I'm getting that error
        channel_name = "/apollo/sensor/{}/compensator/PointCloud2".format(c)
        print("Lidar") 
        
        
What changes can I do? Or what is causing this error?

**Comment by daohu527** [comment]
The reason for the error is that you have the wrong number of parameters.

**Comment by Srikar-Chaganti** [comment]
> The reason for the error is that you have the wrong number of parameters.

The same thing was working when we run with the same number of parameters on nuScenes dataset. 
Is it something I need to look on while I read radiate dataset?

**Comment by daohu527** [comment]
Yes, That may not be a problem with function parameters. When reading files with numpy, you should pay attention to the size of the array, that is, how many bytes are read at a time.

You can give more detailed examples. From the above example, I think you suspect that there is a problem with function parameter passing.
