### ISSUE TITLE
无法解析radar数据

### ISSUE THREAD

**Issue by lxzatwowone1** [daohu527/cyber_record#65]
目前无法解析radar数据，提示“Couldn't find base/device_connect/proto/radar_data.proto”

**Comment by daohu527** [comment]
Can you explain your usage in detail? The record file will carry the proto data format, so I am not sure about your usage scenario.

**Comment by lxzatwowone1** [comment]
OK! when I use cyber_record in terminal to check radar data record,error message as shown in the figure
![today](https://github.com/daohu527/cyber_record/assets/57927067/f3509066-2aec-4612-9ec5-e749be9eeb1c)
Thanks!

**Comment by daohu527** [comment]
The reason for this error is that the proto file cannot be found in the record. Normal record will have this file saved. If not, you may need to recover it. 

below is the method
https://github.com/daohu527/cyber_record?tab=readme-ov-file#recover
