### ISSUE TITLE
Data such as pose.header.timestamp_sec are repeated

### ISSUE THREAD

**Issue by Terencedu** [daohu527/cyber_record#74]
Hello, thank you for sharing! I am having trouble with repeated data when reading ego position information.

1. Why are many data repeated such as "header.timestamp_sec, position, orientation" (figure below)? If I load this record with Apollo, all the data is not repeated, meaning that the original record data is fine.
![image](https://github.com/user-attachments/assets/c75c71f3-b585-4f61-8d44-b0709d82e25f)

![20241125-160121](https://github.com/user-attachments/assets/fad6bbca-62aa-490b-b094-1c47705c7531)

2. What is the difference between "header.timestamp_sec" and "t"? "t" is about 0.02 second greater than "header.timestamp_sec". Is this t the time to save data? I want to save the exact time of pose at that moment, which timestamp data should I use? The final "t" timestamp is not repeated. Thank you!
![image](https://github.com/user-attachments/assets/aedd97d6-2987-484e-9209-c8a1c9e88083)

**Comment by daohu527** [comment]
Could you test another API `read_messages_fallback`?

**Comment by Terencedu** [comment]
Thank you for your reply!

The output of `read_messages_fallback` and  `read_messages` is the same that the poisition data is also repeated. However, when I read radar data with  `read_messages_fallback` and  `read_messages`, data is not repeated.

The total number of position data is correct, there are 3000 pieces of data in 60s, which corresponded to 50hz gps sampling. However, some fields of data are duplicated, including: timestamp_sec, position, orientation, linear_velocity, heading, but linear_acceleration, angular_velocity, linear_acceleration_vrf and angular_velocity_vrf data are not repeated. How to deal with it?

Thank you!

![image](https://github.com/user-attachments/assets/88b08df9-1934-4902-b603-1b3429ab7cc2)

![image](https://github.com/user-attachments/assets/b0675cec-e17e-4dcd-b316-73b1d4f1fbb9)

![image](https://github.com/user-attachments/assets/0d9b13da-ba21-4fc5-b558-ee1a67bc234e)

**Comment by Terencedu** [comment]
The problem is the record data I collected. Your code is right, thank you!
